[project]
name = "layout-overlap"
version = "0.1.0"
description = "HuggingFace Evaluate metric for layout overlap"
readme = "README.md"
authors = [
    { name = "Shunsuke KITADA", email = "shunsuke.kitada.0831@gmail.com" },
]
requires-python = ">=3.11"
dependencies = ["evaluate"]
